### PR TITLE
Update README with supported versions

### PR DESCRIPTION
**Pull request by Jorge-Rodriguez**
##### SUMMARY

Add entries in the README file specifying which versions of Ansible, MySQL/MariaDB and database connectors we actively test against.

- Resolves #141 

##### ISSUE TYPE

- Docs Pull Request

### CODE REVIEW

**Review by Andersson007 — COMMENTED** [review]
@Jorge-Rodriguez thanks for the update!

We usually don't add changelog fragments for doc (and similar) changes.
However, if you think it's worth notifying folks (mostly users) via the changelog, we could add the fragment of course. What do you think?

**Comment by Jorge-Rodriguez** [comment]
> @Jorge-Rodriguez thanks for the update!
> 
> We usually don't add changelog fragments for doc (and similar) changes. However, if you think it's worth notifying folks (mostly users) via the changelog, we could add the fragment of course. What do you think?

It was suggested in #141 that we do so

**Review by Andersson007 — APPROVED** [review]
Ah, thanks for clarifying!
LGTM to merge this after https://github.com/ansible-collections/community.mysql/pull/246

**Comment by Andersson007** [comment]
@rsicart if you're OK with this, feel free to merge

**Review by rsicart — APPROVED** [review]

**Comment by Andersson007** [comment]
@Jorge-Rodriguez thank you for the update! @rsicart thanks for reviewing and merging!

**Comment by Andersson007** [comment]
Should we update the `requirements` section in https://github.com/ansible-collections/community.mysql/blob/main/plugins/doc_fragments/mysql.py adding `mysqlclient`?
If anyone is happy to do it, please go ahead. If no time, let me know.

**Pull request merged**
