### PR TITLE
Fix the collection to work with mysqlclient connector

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible-collections/community.mysql/issues/292

### CODE REVIEW

**Comment by Andersson007** [comment]
I'm debugging the underlying issue now

**Comment by Andersson007** [comment]
@rsicart @Jorge-Rodriguez ready for review (it looks a bit suspicious but anyway CI is green)

**Comment by rsicart** [comment]
Nice! Good job @Andersson007 :)
LGTM :+1:

**Review by rsicart — APPROVED** [review]

**Comment by Andersson007** [comment]
@rsicart thanks for reviewing!

**Comment by Andersson007** [comment]
@bmalynovytch could you please take a look?

**Comment by Andersson007** [comment]
@rsicart thanks for reviewing!
Also a fyi: we backport (only) bugfixes to the supported branches (currently all, i.e. stable-2, stable-1). I'm gonna do it now, no need to review backports. I also backport general changes to docs, README, MAINTAINERS, etc. for consistency

**Comment by Andersson007** [comment]
fyi for saving in bookmarks: the backport manual https://docs.ansible.com/ansible/devel/community/development_process.html#backporting-merged-prs-in-ansible-base (we use `main` instead `devel` resp. as the guide is for ansible-core)

**Pull request merged**
