### PR TITLE
Fix privilege changing everytime

### LINKED ISSUE #77: mysql_user: Granting all privileges at a global level always results in a change in MySQL 8.0
##### SUMMARY
Granting ALL PRIVILEGES at a global level will always result in a change being detected.  I came across this issue when trying to re-enable the `user_password_update_test.yml` test for another change.  This appears to be linked to the following change in MySQL 8.0:

> In MySQL 8.0 compared to previous series, SHOW GRANTS no longer displays ALL PRIVILEGES in its global-privileges output because the meaning of ALL PRIVILEGES at the global level varies depending on which dynamic privileges are defined. Instead, SHOW GRANTS explictly lists each granted global privilege
(https://dev.mysql.com/doc/refman/8.0/en/show-grants.html)

So, because the expanded list of all privileges doesn't match "ALL PRIVILEGES", a change will always be made when applying `*.*:ALL`.  Privileges at the database and/or table level are unaffected (hopefully the more common use case).

This issue appears to be complicated by the fact that dynamic privileges are defined at runtime as per the [docs](https://dev.mysql.com/doc/mysql-security-excerpt/8.0/en/privileges-provided.html#privileges-provided-dynamic).  This isn't my area of expertise, but my understanding of the implication of this is that we cannot reliably hard-code dynamic privileges to check.  `SHOW PRIVILEGES` seems to get us the list of privileges that would be applied to a user with `*.*:ALL` (in addition to `GRANT`, `PROXY`, and `USAGE`).

I can think of a couple of options:

1. This is the desired behavior.  It can be added to the documentation and the test below can be added so the intent is clear.  Possibly a warning?
2. Build the list of privileges to check against using `SHOW PRIVILEGES` when  priv is `*.*:ALL`

Like I mentioned, this isn't my area of expertise, so it is possible that hard-coding the privileges will really work, but purely based on the documentation it seems like it wouldn't.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION
Development

##### CONFIGURATION
Development environment

##### OS / ENVIRONMENT
Development environment

##### STEPS TO REPRODUCE

The following test will fail and reproduce the issue:

```yaml
- vars:
    mysql_parameters: &mysql_params
      login_user: '{{ mysql_user }}'
      login_password: '{{ mysql_password }}'
      login_host: 127.0.0.1
      login_port: '{{ mysql_primary_port }}'

  block:

    - name: Create a user with all privileges
      mysql_user:
        <<: *mysql_params
        name: '{{ user_name_5 }}'
        password: '{{ user_password_5 }}'
        priv: '*.*:ALL'
        state: present
      register: result

    - name: Assert that there was a change because the permissions did not exist previously
      assert:
        that:
          - "result.changed == true"

    - name: Test idempotency when nothing has changed and we're still granting ALL privileges
      mysql_user:
        <<: *mysql_params
        name: '{{ user_name_5 }}'
        password: '{{ user_password_5 }}'
        priv: '*.*:ALL'
        state: present
      register: result

    - name: Assert that there wasn't a change because the user already had ALL privileges
      assert:
        that:
          - "result.changed == false"

    ##########
    # Clean up

    - name: Drop test user
      mysql_user:
        <<: *mysql_params
        name: '{{ user_name_5 }}'
        state: absent
```

##### EXPECTED RESULTS
The test above should pass because no change was made to the privileges.

##### ACTUAL RESULTS

```
TASK [test_mysql_user : Test idempotency when nothing has changed and we're still granting ALL privileges] ***
task path: /root/ansible_collections/community/mysql/tests/output/.tmp/integration/test_mysql_user-sw27zu6h-ÅÑŚÌβŁÈ/tests/integration/targets/test_mysql_user/tasks/test_grant_all_privileges.yml:33
<testhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<testhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<testhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1609109000.0398564-8365-196033537627436 `" && echo ansible-tmp-1609109000.0398564-8365-196033537627436="` echo /root/.ansible/tmp/ansible-tmp-1609109000.0398564-8365-196033537627436 `" ) && sleep 0'
Using module file /root/ansible_collections/community/mysql/plugins/modules/mysql_user.py
<testhost> PUT /root/.ansible/tmp/ansible-local-101glv7bsmi/tmpd7a9ul1t TO /root/.ansible/tmp/ansible-tmp-1609109000.0398564-8365-196033537627436/AnsiballZ_mysql_user.py
<testhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1609109000.0398564-8365-196033537627436/ /root/.ansible/tmp/ansible-tmp-1609109000.0398564-8365-196033537627436/AnsiballZ_mysql_user.py && sleep 0'
<testhost> EXEC /bin/sh -c '/tmp/python-ypi9raas-ansible/python /root/.ansible/tmp/ansible-tmp-1609109000.0398564-8365-196033537627436/AnsiballZ_mysql_user.py && sleep 0'
<testhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1609109000.0398564-8365-196033537627436/ > /dev/null 2>&1 && sleep 0'
changed: [testhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "append_privs": false,
            "ca_cert": null,
            "check_hostname": null,
            "check_implicit_admin": false,
            "client_cert": null,
            "client_key": null,
            "config_file": "/root/.my.cnf",
            "connect_timeout": 30,
            "encrypted": false,
            "host": "localhost",
            "host_all": false,
            "login_host": "127.0.0.1",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_port": 3307,
            "login_unix_socket": null,
            "login_user": "root",
            "name": "db_user5",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "plugin": null,
            "plugin_auth_string": null,
            "plugin_hash_string": null,
            "priv": "*.*:ALL",
            "resource_limits": null,
            "sql_log_bin": true,
            "state": "present",
            "tls_requires": null,
            "update_password": "always",
            "user": "db_user5"
        }
    },
    "msg": "Privileges updated",
    "user": "db_user5"
}

TASK [test_mysql_user : Assert that there wasn't a change because the user already had ALL privileges] ***
task path: /root/ansible_collections/community/mysql/tests/output/.tmp/integration/test_mysql_user-sw27zu6h-ÅÑŚÌβŁÈ/tests/integration/targets/test_mysql_user/tasks/test_grant_all_privileges.yml:42
fatal: [testhost]: FAILED! => {
    "assertion": "result.changed == false",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

### PR DESCRIPTION
**Pull request by rsicart**
##### SUMMARY
Compare privileges from before and after manipulation to determine if a change was made to user privileges.

For the moment, `privileges_equal()` function is very naive. We'll see if we need to do a deeper comparison or use an already existing tool for the job (f.e. deepdiff).

Fixes #77

See #77 for more details.

##### ISSUE TYPE
Bugfix Pull Request

##### COMPONENT NAME
mysql_user

### CODE REVIEW

**Comment by Andersson007** [comment]
@rsicart thanks for the fix!
Could you also please:
- Add a [changelog fragment](https://docs.ansible.com/ansible/devel/community/development_process.html#creating-a-changelog-fragment)
- Fix the sanity issues

```
ERROR: Found 2 pep8 issue(s) which need to be resolved:
ERROR: tests/unit/plugins/module_utils/test_mysql_user.py:107:161: E501: line too long (1286 > 160 characters)
ERROR: tests/unit/plugins/module_utils/test_mysql_user.py:108:161: E501: line too long (1286 > 160 characters)
```
UPDATE: sorry, didn't notice that it's a draft

**Comment by rsicart** [comment]
@Andersson007 ready for review :)

all reviewers are welcome!

**Comment by rsicart** [comment]
BTW I'll add the changelog fragment this morning...

**Review by Andersson007 — APPROVED** [review]
@rsicart great job, it's cool to see changes covered with integration and units!

**Comment by Andersson007** [comment]
cc @betanummeric @laurent-indermuehle could you also please take a look?

**Comment by laurent-indermuehle** [comment]
I'm very happy with this contribution which removes multiple "when: mysql... when: mariadb..." conditions. And a bug!

But the method privileges_equal(before_privs, after_privs) is only a comparison (==). And the only thing the unit test tests is the Python comparison operator. Which we should not test at our level.

What if future version of MySQL and MariaDB changes the way they handle privileges? We will have new bugs without knowing.

I would prefer to replace the call to privileges_equal with a simple == in the module, remove the unit test and the method. Then replace this with integration tests that validate that grants are added, revoked, entirely, partially and with all supported database engine.

**Comment by rsicart** [comment]
> But the method privileges_equal(before_privs, after_privs) is only a comparison (==). And the only thing the unit test tests is the Python comparison operator. Which we should not test at our level.

Yes, before beginning this PR I thought I'd need a more complex function, comparing key by key, list by list, or something like that. Finally it seems that a comparison makes it.
 
> What if future version of MySQL and MariaDB changes the way they handle privileges? We will have new bugs without knowing.

That's what happened with 'ALL PRIVILEGES' translation.

> I would prefer to replace the call to privileges_equal with a simple == in the module, remove the unit test and the method.

I can do that if you prefer, it makes sense to me also.

> Then replace this with integration tests that validate that grants are added, revoked, entirely, partially and with all supported database engine.

I think there's already some tests for privilege replace, append and subtract. Don't they cover already what you comment? Perhaps that should be a new issue to improve integration test suite.

**Comment by laurent-indermuehle** [comment]
>> Then replace this with integration tests that validate that grants are added, revoked, entirely, partially and with all supported database engine.

> I think there's already some tests for privilege replace, append and subtract. Don't they cover already what you comment? Perhaps that should be a new issue to improve integration test suite.

My bad, I didn't checked the 21 (!!!) files inside tests/integration/targets/test_mysql_user/tasks.
Many cases are covered already and we can always add more tests later if issues arise.

lgtm! Thanks for the modifications!

**Review by laurent-indermuehle — APPROVED** [review]

**Comment by betanummeric** [comment]
I like the validation by comparing the existing privileges before and after the grant/revoke. :+1: 

For the record, MariaDB is also very chaotic when it comes to privileges (see https://mariadb.com/kb/en/grant/):

- aliased privileges
  - `ALL` results in `ALL PRIGVILEGES`
  - `REPLICATION REPLICA` results in `REPLICATION SLAVE`
- `USAGE` grants nothing and can be ignored (only sometimes necessary for syntactic reasons)

> BINLOG MONITOR
> New name for [REPLICATION CLIENT](https://mariadb.com/kb/en/grant/#replication-client) from [MariaDB 10.5.2](https://mariadb.com/kb/en/mariadb-1052-release-notes/), (REPLICATION CLIENT still supported as an alias for compatibility purposes). Permits running SHOW commands related to the [binary log](https://mariadb.com/kb/en/binary-log/), in particular the [SHOW BINLOG STATUS](https://mariadb.com/kb/en/show-binlog-status/) and [SHOW BINARY LOGS](https://mariadb.com/kb/en/show-binary-logs/) statements. Unlike [REPLICATION CLIENT](https://mariadb.com/kb/en/grant/#replication-client) prior to [MariaDB 10.5](https://mariadb.com/kb/en/what-is-mariadb-105/), [SHOW REPLICA STATUS](https://mariadb.com/kb/en/show-replica-status/) isn't included in this privilege, and [REPLICA MONITOR](https://mariadb.com/kb/en/grant/#replica-monitor) is required.

> The SUPER privilege has been split into multiple smaller privileges from [MariaDB 10.5.2](https://mariadb.com/kb/en/mariadb-1052-release-notes/) to allow for more fine-grained privileges, although it remains an alias for these smaller privileges.

But implementing special logic for this mess would only make sense to avoid an unwanted revocation, like we did in PR #434 for the `ALL` privilege. The module revokes privileges before granting others, so we need to be careful not to create a time where a wanted privilege is removed.

**Comment by rsicart** [comment]
Thank you @Andersson007 @laurent-indermuehle @betanummeric for reviewing! :)

**Comment by Andersson007** [comment]
@rsicart thanks for the contribution!
@betanummeric @laurent-indermuehle thanks for reviewing!

**Comment by Andersson007** [comment]
1. Should we backport this? If yes, @rsicart feel free to put the `backport-1` and `backport-2` labels
2. I was fast and [announced](https://github.com/ansible-collections/community.mysql/issues/77#issuecomment-1241531495) that it was in the latest release which is not true but anyway, we should release the collection (after backporting the fix if needed).

**Comment by rsicart** [comment]
> 1. Should we backport this?

I'm not sure @Andersson007, this PR fixes code introduced by #333 which was not backported.

**Comment by Andersson007** [comment]
> > 1. Should we backport this?
> 
> I'm not sure @Andersson007, this PR fixes code introduced by #333 which was not backported.

@rsicart ah, ok, doesn't need then, thanks for the info

**Comment by laurent-indermuehle** [comment]
I tried to patch stable-2 with your changes and all integrations tests pass. But there is less tests in stable-2. I would not be confident to backport this.

**Comment by betanummeric** [comment]
stable-1 subtracts existing from requested privileges and grants those assuming a change, so in theory it is affected by the false change bug as well. But I would say it's too much effort to backport.

**Comment by Andersson007** [comment]
> I tried to patch stable-2 with your changes and all integrations tests pass. But there is less tests in stable-2. I would not be confident to backport this.

@laurent-indermuehle if the related code was introduced in https://github.com/ansible-collections/community.mysql/pull/333, we must not backport the fix as it relates to a new feature introduced in 3.*.* (we don't backport new features, so the related code isn't present in stable-2 and stable-1

**Comment by Andersson007** [comment]
i wouldn't touch the other branches if it's not impossible to backport it with just `git cherry-pick -x <commitNum>`

**Comment by Andersson007** [comment]
sorry, forgot to draft a release for 3.5.0 last time, just did it.
Does anyone want to release 3.5.1 ?

**Comment by rsicart** [comment]
I'll do it.

**Pull request merged**
