### PR TITLE
Adds support for show binary log status statement

### PR DESCRIPTION
**Pull request by dennisurtubia**
##### SUMMARY
Adds support for show binary log status statement.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
`mysql_replication`

##### ADDITIONAL INFORMATION
`SHOW MASTER STATUS` was replaced by `SHOW BINARY LOG STATUS`. [Doc](https://dev.mysql.com/doc/refman/8.3/en/show-binary-log-status.html)

### CODE REVIEW

**Comment by dennisurtubia** [comment]
Feature asked on https://github.com/ansible-collections/community.mysql/issues/635#issuecomment-2127358039

**Comment by dennisurtubia** [comment]
@Andersson007 @laurent-indermuehle I tried to implement an integration test checking the executed query, but it don't works, seems that `getprimary` mode never returns executed queries.

I think the implemented integration tests are sufficiently to test `getprimary` mode, however, I think it's important to configure in our actions pipeline to execute `MySQL >= 8.2.0`

**Review by Andersson007 — APPROVED** [review]
@dennisurtubia LGTM, thanks for the contribution?

@laurent-indermuehle please take a look

**Comment by eRadical** [comment]
Hi @dennisurtubia,

If we're here can we also extend for MariaDB >= 10.5.2 with:

```
if get_server_implementation(cursor) == "mariadb" and LooseVersion(version) >= LooseVersion("10.5.2"):
        term = "BINLOG"
```

Ref.: [SHOW BINLOG STATUS](https://mariadb.com/kb/en/show-binlog-status/)

Regards!

**Review by Andersson007 — APPROVED** [review]
@eRadical great feedback, approved the PR again, thanks! waiting for @laurent-indermuehle 's feedback

**Comment by dennisurtubia** [comment]
> Hi @dennisurtubia,
> 
> If we're here can we also extend for MariaDB >= 10.5.2 with:
> 
> ```
> if get_server_implementation(cursor) == "mariadb" and LooseVersion(version) >= LooseVersion("10.5.2"):
>         term = "BINLOG"
> ```
> 
> Ref.: [SHOW BINLOG STATUS](https://mariadb.com/kb/en/show-binlog-status/)
> 
> Regards!

Hey, @eRadical thank you for your suggestion! Done.

**Review by laurent-indermuehle — APPROVED** [review]

**Comment by laurent-indermuehle** [comment]
The code starts to be really beautiful! Thanks for your contributions @eRadical and @dennisurtubia!

**Comment by Andersson007** [comment]
@dennisurtubia thanks a lot for the improvement!
@eRadical @laurent-indermuehle thanks for reviewing!

**Pull request merged**
