### PR TITLE
Remove support for REQUIRESSL privilege

### PR DESCRIPTION
**Pull request by Jorge-Rodriguez**
##### SUMMARY

Remove support for the `REQUIRESSL` privilege as the handling of the connection requirement via privileges is an antipattern and it has been superseded by the `tls_requires` option

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

mysql_user

### CODE REVIEW

**Comment by Andersson007** [comment]
@Jorge-Rodriguez could you please resolve the conflicts?

**Comment by Jorge-Rodriguez** [comment]
@Andersson007 done. Codecov errors

**Review by Andersson007 — APPROVED** [review]
LGTM thank you much @Jorge-Rodriguez for doing this!

**Comment by Andersson007** [comment]
@bmalynovytch @rsicart this is a [planned breaking change](https://github.com/ansible-collections/community.mysql/issues/101) (for 3.0.0, which I'm gonna release this week hopefully). Would you like to take a look too?

**Comment by Andersson007** [comment]
@Jorge-Rodriguez thanks for working on this!

**Pull request merged**
