### PR TITLE
mysql_user: deprecate alias user for name argument

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible-collections/community.mysql/issues/669.
It wasn't even documented, the failures are addressed in https://github.com/ansible-collections/community.mysql/pull/668

### CODE REVIEW

**Comment by Andersson007** [comment]
ready for review

**Comment by Andersson007** [comment]
if we wanna merge this, https://github.com/ansible-collections/community.mysql/pull/668 should go first, then I'll rebase it

**Comment by Andersson007** [comment]
ready for review

**Comment by samccann** [comment]
Not really qualified for an official review, but the changes make sense to me.

**Comment by laurent-indermuehle** [comment]
I'm not super fan of removing an alias afterward.
But I parsed all my code base and it turns out, I only use 'name'. Not surprised because it's the default for Ansible modules after all.

So for simplification sake, let's merge this! :)
Thanks @Andersson007 for the work!

**Comment by Andersson007** [comment]
@samccann @laurent-indermuehle thanks for reviewing!

**Pull request merged**
