### PR TITLE
Fix role integration tests for mariadb

### LINKED ISSUE #260: Test roles on mariadb
##### SUMMARY
Integration tests for target `test_mysql_role` are only played for mysql.
We shoud do the same tests for mariadb.

This Issue is related to https://github.com/ansible-collections/community.mysql/pull/246

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mariadb integration tests

##### ANSIBLE VERSION

```paste below
ansible 2.10.15
  config file = None
  configured module search path = ['/home/rsicart/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rsicart/virtualenvs/ansible/venv_2_10_7/lib/python3.7/site-packages/ansible
  executable location = /home/rsicart/virtualenvs/ansible/venv_2_10_7/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
```

##### COLLECTION VERSION

```paste below
(venv_2_10_7) rsi-oxalide k8s:rsi-sandbox  :: ~ » ansible-galaxy collection list community.mysql  

# /home/rsicart/virtualenvs/ansible/venv_2_10_7/lib/python3.7/site-packages/ansible_collections
Collection      Version
--------------- -------
community.mysql 3.0.0
```

##### CONFIGURATION

```paste below
(venv_2_10_7) rsi-oxalide k8s:rsi-sandbox  :: ~ » ansible-config dump --only-changed
(venv_2_10_7) rsi-oxalide k8s:rsi-sandbox  :: ~ »
```

##### OS / ENVIRONMENT

Debian Buster

##### STEPS TO REPRODUCE

```yaml
ansible-test integration test_mysql_role --docker quay.io/ansible/default-test-container:4.1.1 -v
```

##### EXPECTED RESULTS

Integration tests for target `test_mysql_role` are not executed on mariadb.

##### ACTUAL RESULTS

Integration tests for target `test_mysql_role` should be executed on mariadb.

```paste below
N/A
```

### PR DESCRIPTION
**Pull request by rsicart**
##### SUMMARY
Fixes #260 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
Integration tests for target `test_mysql_role`

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by rsicart** [comment]
Hey @Andersson007 @Jorge-Rodriguez @bmalynovytch
I added you as possible reviewers, nothing urgent, feel free to ignore if you do not have time.
Thanks in advance!

**Comment by rsicart** [comment]
Sorry for the noise, I'll try to fix that before asking your review next time...

**Comment by Andersson007** [comment]
@rsicart thank you for this very important fix! Yep, please, when it ready, let us know

**Comment by rsicart** [comment]
I don't know why mariadb with mysqlclient doesn't work, so I excluded that from test matrix... Do not hesitate if you know how to fix that properly!
Tests are passing now :)

@Andersson007 @Jorge-Rodriguez @bmalynovytch ready for review

**Review by Andersson007 — APPROVED** [review]

**Comment by Andersson007** [comment]
> I don't know why mariadb with mysqlclient doesn't work, so I excluded that from test matrix... Do not hesitate if you know how to fix that properly! Tests are passing now :)

@rsicart thanks for fixing the CI! Yep, let's do it incrementally.
When the PR gets merged, could you please update the issue (or create a new one) to commit somewhere that it doesn't work with `mysqlclient`. Later someone will take a look.

Also let's wait until tomorrow for the folks' feedback. If no objections, we'll merge it tomorrow.

Thank you much!

**Comment by Andersson007** [comment]
@rsicart thank you for contributing to the CI part of the collection, this is extremely important for the collection's stability! Really hard to underestimate.
If you create an issue `mysqlclient doesn't work with mariadb` with the info that it's disabled in this PR, it would be great, thank you!

**Pull request merged**
