### PR TITLE
Is changed

### PR DESCRIPTION
**Pull request by laurent-indermuehle**
##### SUMMARY
Change tests comparison of "changed" and "failed" with == "true" by:
- is changed
- is not changed
- is succeeded
- is failed

##### ISSUE TYPE

- Lint 

##### COMPONENT NAME

CI

##### ADDITIONAL INFORMATION

For consistency, indentation for assert module has been formatted.

### CODE REVIEW

**Comment by laurent-indermuehle** [comment]
Hello @Andersson007,
When I click "Rerun now" here : https://github.com/ansible-collections/community.mysql/pull/427/checks?check_run_id=7952294617 
Nothing happens, do I miss rights to rerun Codecov?

**Comment by Andersson007** [comment]
> Hello @Andersson007, When I click "Rerun now" here : https://github.com/ansible-collections/community.mysql/pull/427/checks?check_run_id=7952294617 Nothing happens, do I miss rights to rerun Codecov?

hi @laurent-indermuehle, in such cases, just ignore codecov:)

**Review by Andersson007 — APPROVED** [review]

**Comment by Andersson007** [comment]
Feel free to merge and backport, thanks for working on this! codecov is the only test we can have red when merging

**Comment by laurent-indermuehle** [comment]
@Andersson007 thanks for the explanation. I thought the grey button isn't clickable ;)

**Pull request merged**
