### PR TITLE
Fix CI for roles

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fix CI for roles.
They've recently started failing. As we don't have roles anyway, if the first attempt doesn't help, I'll just remove the file.

### CODE REVIEW

**Comment by rsicart** [comment]
😳
What's the purpose of this pipeline? Testing Ansible installation with different available python versions?

**Comment by Andersson007** [comment]
> flushed What's the purpose of this pipeline? Testing Ansible installation with different available python versions?

Thanks for the question! As collections can also contain roles, i think it was originally added just "in advance". There's a commented command at the bottom of the file. We don't have any roles at the moment but, I guess, if once we have some, we'll need to uncomment the command.
I was thinking about removing the file or renaming it but it doesn't require a lot of resources and i decided to leave it there. Might be useful in the future.
What do you think? I'm not against of removing but, on the other hand, it doesn't require a lot to have it there.

**Comment by rsicart** [comment]
Ahhh yes, thanks. We are talking about ansible roles, it makes sense :) . I agree, let's keep it.
LGTM 👍

**Review by rsicart — APPROVED** [review]

**Comment by Andersson007** [comment]
@rsicart thanks for reviewing and merging!

**Pull request merged**
