### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Update README.md:
- Move contributing section to the top, expand it.
- Add the Code of Conduct and Governance section.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
README.md

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @bmalynovytch @Jorge-Rodriguez (if it's ok for you, feel free to merge or suggest improvements. I didn't elaborate on this much.).

**Comment by Andersson007** [comment]
@bmalynovytch @Jorge-Rodriguez I have just also added the `MAINTAINERS` file. The order is as is not because I want to be mentioned more often then you:)) It's alphabetical.
Ready for review

**Comment by bmalynovytch** [comment]
> @bmalynovytch @Jorge-Rodriguez I have just also added the `MAINTAINERS` file. The order is as is not because I want to be mentioned more often then you:)) It's alphabetical.
> Ready for review

I think placing the group leader first would be better 🤔 
😝

**Review by bmalynovytch — APPROVED** [review]

**Comment by Andersson007** [comment]
@bmalynovytch thanks for reviewing and merging!:) Feel free to place:)

**Pull request merged**
