### PR TITLE
[stable-1] Backports

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Backport of https://github.com/ansible-collections/community.mysql/pull/279 and https://github.com/ansible-collections/community.mysql/pull/323

### CODE REVIEW

**Comment by rsicart** [comment]
:1st_place_medal:

**Comment by Andersson007** [comment]
@rsicart there were a few merge conflicts, so the bot couldn't merge it and it required manual backports. Just a fyi:)

**Comment by rsicart** [comment]
Yes, thanks, I saw that the bot gives some hints on how to proceed to fix conflicts manually, that's so cool 😎

**Comment by Andersson007** [comment]
> Yes, thanks, I saw that the bot gives some hints on how to proceed to fix conflicts manually, that's so cool

yep, thanks to webknjaz

**Pull request merged**
