### PR TITLE
Setup patchback bot config file (resolves #310)

### LINKED ISSUE #310: Patchback bot
##### SUMMARY
As discussed with @Andersson007, setting up [patchback bot](https://github.com/sanitizers/patchback-github-app) to backport PRs from `main` to other `stable-*` branches could save a lot of time.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Patchback bot

##### ADDITIONAL INFORMATION

The main objective is saving time when releasing the collection.

It's used in other collections like [c.general](https://github.com/ansible-collections/community.general/blob/main/.github/patchback.yml), **felixfontein** gave us a good feedback (thanks!) and he's happy with this bot.

In c.general, the branches are named `stable-X`, and the labels are `backport-X`, just like ours. When we put labels on PRs there like, for example, backport-1, the bot will create a backport for stable-1.

The bot needs to be enabled for the repo by someone with enough rights one the configuration file `.github/patchback.yml` is setup.

Patchback bot run somewhere on the cloud, and **webknjaz** takes care of it.

So, the **main steps** to get it working are:

1. create bot configuration file `.github/patchback.yml`
2. enable the app

```yaml

```

### PR DESCRIPTION
**Pull request by rsicart**
##### SUMMARY

Create patchback bot configuration file.

See #310 for more details.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

Patchback bot

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]
LGTM thanks @rsicart !

**Comment by Andersson007** [comment]
Cool, works:) Thanks @rsicart !

**Comment by Andersson007** [comment]
@rsicart feel free to create `backport-1` label and backport this PR and merge it to stable-1 for consistency

**Comment by rsicart** [comment]
> @rsicart feel free to create `backport-1` label and backport this PR and merge it to stable-1 for consistency

Done! That was fast and easy! :)

**Comment by rsicart** [comment]
> Cool, works:) Thanks @rsicart !

You're welcome, it was interesting to work on that.

And backporting PRs from now on will be easier :D

**Comment by Andersson007** [comment]
>And backporting PRs from now on will be easier :D

Yep, will save a lot of time!

**Pull request merged**
