### PR TITLE
Add PSF-license.txt file

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
plugins/module_utils/_version.py mentions PSF-license.txt, which doesn't exist yet.

Please make sure to create new releases with this ASAP.

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME
licenses

### CODE REVIEW

**Review by gotmax23 — APPROVED** [review]
I would squash these commits, but the content of the PR looks okay, so this is approved (although I don't think my approval actually counts for anything).

**Comment by felixfontein** [comment]
@gotmax23 PRs are squashed on merge anyway.

**Comment by gotmax23** [comment]
> @gotmax23 PRs are squashed on merge anyway.

Fair enough. I thought that might be the case.

**Comment by Andersson007** [comment]
Fixes https://github.com/ansible-collections/community.mysql/issues/357

**Review by Andersson007 — APPROVED** [review]

**Comment by Andersson007** [comment]
@felixfontein thanks for the fix!
@gotmax23 thanks for reviewing!

**Comment by felixfontein** [comment]
I created manual backports in #359 and #360.

**Pull request merged**
