### PR TITLE
mysql_user: fix broken compatibility for priviledge aliases

### LINKED ISSUE #232: Unable to create user with privilege REPLICATION CLIENT on MariaDB 10.5.5
##### SUMMARY
When trying to create a new user using the mysql_user module it error if you try to user REPLICATION CLIENT as a priv. As per the MariaDB docs this was renamed in v10.5.2 to BINLOG MONITOR but the old name should alias to this. In v2.1.0 of community.mysql it works as intended but in v2.3.0 it errors.

It would be nice to be able to run the same Ansible against a MariaDB 10.4 and 10.5 server.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.mysql.mysql_user

##### ANSIBLE VERSION

```
ansible [core 2.11.6]
config file = /codebuild/output/src941743992/src/ansible.cfg
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/local/bin/ansible
python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
jinja version = 3.0.2
libyaml = True
```

##### COLLECTION VERSION

```
community.mysql 2.3.0
```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

OS Ubuntu 20.04.3 LTS
MariaDB 10.5.5

##### STEPS TO REPRODUCE

```yaml
- name: "Create user"
  mysql_user:
    name: "user"
    host: "localhost"
    password: "password"
    login_user: root
    login_password: "password"
    priv: "*.*:SELECT,PROCESS,SHOW DATABASES,SHOW VIEW,EXECUTE,SUPER,CREATE TEMPORARY TABLES,LOCK TABLES,REPLICATION SLAVE,REPLICATION CLIENT,EVENT,TRIGGER,RELOAD"
    state: present
```

##### EXPECTED RESULTS

User created with privileges set as above.

##### ACTUAL RESULTS

Error received as below

```paste below
 TASK [ansible-mariadb : Create user] **************************
fatal: [hostname]: FAILED! => changed=false 
  msg: 'invalid privileges string: Invalid privileges specified: frozenset([''REPLICATION CLIENT''])' 
```

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.mysql/issues/232

- Before 2.3.0 all supported privs were hardcoded in the `VALID_PRIVS` frozenset.
- Since 2.3.0 all supported privs are fetched from the server dynamically with the `SHOW PRIVILEGES` command.
- The issue is that some privs were deprecated, replaced and became aliases and they are not present in the `SHOW PRIVILEGES` output but they were present in the `VALID_PRIVS` frozenset.
- Removing `VALID_PRIVS` has brought breaking changes.

This PR:
1) returns `VALID_PRIVS` removed in https://github.com/ansible-collections/community.mysql/pull/217
2) merges it in a frozenset with `show_privs` (fetched from server dynamically) and `EXTRA_PRIVS`
3) now the frozenset contains all the privs including the hardcoded ones that were there before 2.3.0

##### ISSUE TYPE
- Bugfix Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
@jb-2197 @tuhoanganh as i mentioned in the issue, we don't have mariadb in our CI, so could you please help with testing?
The easiest way how to do it (in this case) is:
0. Run you playbook again to make sure it fails
1. Find the `community/mysql/plugins/module_utils/users.py` on your test system
2. Backup it
3. Add the changes from this PR
4. Run the playbook again and confirm that this fixes the problem
5. Return the original (backed up) file in place

More complex method is described [there](https://github.com/ansible/community-docs/blob/main/test_pr_locally_guide.rst)

**Comment by Andersson007** [comment]
ready_for_review

**Review by bmalynovytch — APPROVED** [review]

**Comment by Andersson007** [comment]
@bmalynovytch thanks for reviewing and merging! I'll release the patch (i.e. `2.3.1`) morning

**Comment by rsicart** [comment]
Sorry I'm late for the conversation :/ . If I understand, there are some alias privileges we lost when merging #217 . Having a hard coded list of alias privileges merged with the dynamic privilege list could be enough?

**Comment by rsicart** [comment]
But what you commented in https://github.com/ansible-collections/community.mysql/issues/232#issuecomment-945547943 makes sense and it deserves reflexion.

**Comment by Andersson007** [comment]
@rsicart https://github.com/ansible-collections/community.mysql/issues/234 let's continue to discuss this in the issue:)

**Comment by tuhoanganh** [comment]
@Andersson007  Sorry for the late reply :(
i followed your guide and try to test new code with my test environment
OS: MacOS Bigsur
```
Darwin MF843.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
```

ANSIBLE VERSION
```
ansible [core 2.11.6]
  config file = /Volumes/Work/git/SVTECH-installation-automation/ansible.cfg
  configured module search path = ['/Users/hoangtu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /Volumes/Work/git/test-automation/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.12 (default, Oct 13 2021, 06:42:42) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
```

COLLECTION VERSION
```
community.mysql 2.3.0
```

PR APPLIED
```
#233 
```

INVENTORY FILE
```
all:
  children:
    replication:
      children:
        replication_master:
          hosts:
            db-01:
              ansible_host: 10.98.10.161
              IP: 10.98.10.161
              server_id: 1
        replication_slave:
          hosts:
            db-02:
              ansible_host: 10.98.10.162
              IP: 10.98.10.162
              server_id: 2
            db-03:
              ansible_host: 10.98.10.163
              IP: 10.98.10.163
              server_id: 3
          vars:
            Is_Slave: true
            backup_dir: /tmp/mariabackup
      vars:
        gtid_domain: 1
        replication_user:
          name: "repl_user"
          host: "%"
          password: "repl_user@123"
          priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
```

STEPS TO REPRODUCE
```
- name: DATABASE [Replication]  - Ensure replication user exists on master.
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: "{{ data_dir }}/mysql.sock"
    name: "{{ replication_user.name }}"
    host: "{{ replication_user.host | default('%') }}"
    password: "{{ replication_user.password }}"
    priv: "{{ replication_user.priv }}"
    update_password: on_create
    state: present
```

EXPECTED RESULTS
```
User created with privileges set as above.
```

ACTUAL RESULTS
```
TASK [database : DATABASE [Replication] - Ensure replication user exists on master.] ***********************************************************************************************************
changed: [db-01 -> db-01]
```

SUMMARY
#233 fixed the problem 👍

**Comment by Andersson007** [comment]
@tuhoanganh ah, no problem at all! We were fast this time:) and I haven't released the patch yet, we'll do it today later.
Thank you for the confirmation, this is much appreciated!

**Pull request merged**
