### PR TITLE
Handle divergences between MySQL and MariaDB

### PR DESCRIPTION
**Pull request by Jorge-Rodriguez**
##### SUMMARY

This is an initial proposal on how to handle the growing divergences between MariaDB and MySQL while keeping the module codebase as clean as possible.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

mysql collection

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Jorge-Rodriguez** [comment]
@Andersson007 @bmalynovytch @bmildren This is my initial (non-working) proposal on the matter above. I'm submitting this draft for your review and comments before tackling further changes and making it actually functional. Thanks in advance for your feedback.

**Comment by Andersson007** [comment]
@Jorge-Rodriguez looks interesting.
it's not related to this PR: If you write to me a test email to aaklychkov at mail dot ru, it would be really great. I won't bother you requesting reviews, etc. via it, it's just for discussing general things rarely. Thanks!

**Comment by bmalynovytch** [comment]
The approach looks good to me for now 👍

**Comment by Jorge-Rodriguez** [comment]
I think it makes more sense to leave this PR as is, just laying out the boilerplate work for future development.
The current conditional branches for MySQL/MariaDB are already transitioned, but I would refrain from doing any further development now.

**Comment by Andersson007** [comment]
cc @bmalynovytch

**Review by Andersson007 — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@Jorge-Rodriguez please resolve the conflict

**Comment by Andersson007** [comment]
@Jorge-Rodriguez after you resolve the conflict, i think we could merge it. I emailed Benjamin 3 days ago. The tests passed, so i think it won't break anything.

**Review by bmalynovytch — APPROVED** [review]

**Comment by bmalynovytch** [comment]
This looks really good, a part from the code duplication, but we can't do much about it 🙁

**Comment by bmalynovytch** [comment]
> I emailed Benjamin 3 days ago. The tests passed, so i think it won't break anything.

I know I'm a bit slow these days, no need to point it out 😝  (just kidding)

**Comment by Andersson007** [comment]
> > I emailed Benjamin 3 days ago. The tests passed, so i think it won't break anything.
> 
> I know I'm a bit slow these days, no need to point it out  (just kidding)

Okay:) Anyway I didn't imply "Shame on @bmalynovytch":))))
It's just "he's informed", so, as in my country people sometimes say for fun, "silence is a sign of agreement":)))

**Comment by Jorge-Rodriguez** [comment]
Rebased and fixed the conflict.
@Andersson007 do we need a documentation fragment for this?

**Comment by Andersson007** [comment]
@Jorge-Rodriguez ah, yes, we need (we don't need it for doc changes only), thanks for reminding:)

**Comment by Andersson007** [comment]
yeah, we must always remember about the fragments when going to merge someone's PR...

**Comment by Jorge-Rodriguez** [comment]
> yeah, we must always remember about the fragments when going to merge someone's PR...

We should add that to the wiki. Do you have the link to the relevant documentation from the developer guide? I always have trouble finding the article about changelog fragments

**Comment by Andersson007** [comment]
@Jorge-Rodriguez https://docs.ansible.com/ansible/devel/community/development_process.html#creating-a-changelog-fragment

**Comment by Andersson007** [comment]
@Jorge-Rodriguez thanks for the refactoring!
@bmalynovytch thanks for reviewing!

**Pull request merged**
