### PR TITLE
[DRAFT] modules: add charset connection option

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible-collections/community.mysql/issues/140

### CODE REVIEW

**Comment by Andersson007** [comment]
@emper0r 
the tests are failing now. It can be because of the databases used for testing.

You could:
1) find and change the files I changed in your system (all except mysql_query and which contain `test` in their path
2) change them similarly and provide your feedback if it helped solve the problem
3) add `charset: utf8mb4` option to your tasks

Thanks

**Comment by Andersson007** [comment]
use a test server:)

**Comment by emper0r** [comment]
i'm sorry,... still didn't work,... 

I'm using [mysql_user.py](https://gist.github.com/emper0r/5d7d55cb325e78ce6f280d8a92651eb5) from 2.10.7 and is very different with your `mysql_user.py`, in any case I backup my version file... and user yours overwriting and playbook still send password to changed but still getting the wrong symbol before will be hashed.

**Comment by Andersson007** [comment]
@emper0r could you also please add ``charset=charset`` to connect function in mysql_user.py a bit below. There's the second conditional invocation and try again

**Comment by Andersson007** [comment]
Right before going to pymysql, the connection dict looks like "{'host': '127.0.0.1', 'port': 3307, 'user': 'db_user5', 'password':
'********', 'connect_timeout': 30, 'charset': 'utf8mb4'}". So it definitely gets into pymysql.connection() as we can see in the code.

@emper0r have you tried all the suggestions listed https://stackoverflow.com/questions/43830160/how-to-finally-set-utf8mb4-properly-on-mysql and https://stackoverflow.com/questions/38363566/trouble-with-utf-8-characters-what-i-see-is-not-what-i-stored ? (try it after adding the thing from my previous comment)

**Comment by emper0r** [comment]
MySQL server is already on utfmb4. 

```
mysql> SHOW SESSION VARIABLES LIKE '%character%';
+--------------------------+-------------------------------------+
| Variable_name            | Value                               |
+--------------------------+-------------------------------------+
| character_set_client     | utf8mb4                             |
| character_set_connection | utf8mb4                             |
| character_set_database   | utf8mb4                             |
| character_set_filesystem | binary                              |
| character_set_results    | utf8mb4                             |
| character_set_server     | utf8mb4                             |
| character_set_system     | utf8                                |
| character_sets_dir       | /usr/share/percona-server/charsets/ |
+--------------------------+-------------------------------------+
8 rows in set (0.00 sec)
```

please send me a raw file with whole code to overwrite my mysql_user.py because I don't understand what connect charset line have to add.

**Comment by Andersson007** [comment]
@emper0r I updated the PR, see "Files changed" `plugins/modules/mysql_user.py` line 1118

**Comment by Andersson007** [comment]
and as we can see in "Some checks were not successful" all the tests that use mysqlclient connector have been passed successfully and all that use pymysql have failed... strange, isn't it?

**Comment by Andersson007** [comment]
Continuing my investigation, I installed mysql 8.0 (its charset is as mentioned above by default) and tried to use the same approach a the module uses (the first symbol of the password used is `£`):
```
mysql> SELECT CONCAT('*', UCASE(SHA1(UNHEX(SHA1('£gadfFDSdtTU^Sdfuj12')))));
+----------------------------------------------------------------+
| CONCAT('*', UCASE(SHA1(UNHEX(SHA1('£gadfFDSdtTU^Sdfuj12')))))  |
+----------------------------------------------------------------+
| *F5A590C9C6C848F242F30641A29B6A13541E28AA                      |
+----------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> create user 'test1'@'localhost' identified with mysql_native_password AS '*F5A590C9C6C848F242F30641A29B6A13541E28AA';
Query OK, 0 rows affected (0.02 sec)

mysql> ^DBye
[aklychko@localhost ~]$ mysql -utest1 -p£gadfFDSdtTU^Sdfuj12
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 19
Server version: 8.0.23 MySQL Community Server - GPL

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```
So in conjunction with that with the mysqlclient connector everything works as expected but that with pymysql it fails.. I don't know what to think:)

**Comment by emper0r** [comment]
In fact.. if you do manually works... but using connector didn't... it's possible would be a bug con mysql-connector wrote on .c from mysql... ? and then when your module use that with mysql_connector.c fail ?, because when I receive on logs never come `£`.... I receive the other symbol so then password crash.

**Comment by Andersson007** [comment]
@emper0r could you please uninstall pymysql and try https://pypi.org/project/mysqlclient/ ?

**Comment by emper0r** [comment]
I already tested but I'm using CentOS 8 and that package can't install.. the output errors say: need dependencies on this centos version 8 didn't exist
` sudo yum install python3-devel mysql-devel`
so we install using ansible MySQL-python3 to use the module

**Comment by Andersson007** [comment]
@emper0r so you didn't check how it works with mysqlclient, right? Would be good to check with mysqldb or mysqlclient connectors. If i have time on the weekend, maybe I'll check.
I'm not sure I understand right, do you have any workarounds now?

**Comment by Andersson007** [comment]
@Jorge-Rodriguez @bmalynovytch any ideas on the issue?

**Comment by emper0r** [comment]
Any workaround? yes.. delete '£' from password string.. and using only ascii characters not that ones in utf8..

**Comment by Jorge-Rodriguez** [comment]
@emper0r what are the python versions on the TARGET hosts for CentOS 7 and 8?

**Comment by emper0r** [comment]
For 7 works Ok using:
```
CentOS Linux release 7.5.1804 (Core)

Python 2.7.5

RPM: MySQL-python-1.2.5-1.el7.x86_64
```

For 8 not works using:
```
CentOS Linux release 8.3.2011

Python 3.8.3

RPM: python3-mysql-1.4.6-5.el8.x86_64
```

**Comment by Jorge-Rodriguez** [comment]
@emper0r that's good news, string encoding changed dramatically in python 3, this gives us a vantage point to investigate. I can have a look over the weekend.

**Comment by Andersson007** [comment]
as this does not fix the issue and it's probably related to PyMySQL + Python3 combination, i'm closing the PR

**Pull request closed without merging**
