### PR TITLE
mysql: revert changes made in PR 116

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
mysql: revert changes made in PR #116 

relates to #116 and https://github.com/ansible-collections/community.mysql/issues/151

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
plugins/module_utils/mysql.py

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @Jorge-Rodriguez

**Review by Jorge-Rodriguez — APPROVED** [review]
So Ansible devel is python 3.8 only now?

**Comment by Andersson007** [comment]
> So Ansible devel is python 3.8 only now?

Good question. Let's wait for updates a bit.
If there's no any updates how to cope with it until next week, we should start figuring out how to fix them.

**Comment by Andersson007** [comment]
@Jorge-Rodriguez if you know a quick solution, welcome.

**Comment by Jorge-Rodriguez** [comment]
> @Jorge-Rodriguez if you know a quick solution, welcome.

It should be possible to exclude the matrix branches for older python versions and Ansible devel

I can do that. I'm planning to tweak the job matrix to include MariaDB.

**Pull request merged**
