### PR TITLE
README.md: Add link to IRC

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
README.md: Add link to IRC

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @bmalynovytch @Jorge-Rodriguez 
if you're in IRC as me, please add your nicknames by proposing changes here if you like.
If you don't, please approve / suggest something to change

**Review by Jorge-Rodriguez — APPROVED** [review]
How alive is IRC these days? Last time I dropped by there was a great deal of sleepers. I'm wondering if it makes sense to move the conversation to a different platform.

**Comment by Andersson007** [comment]
@Jorge-Rodriguez it's alive and active. I'm always there as well as many other folks. It was recently decided to move to Libera.Chat https://github.com/ansible-community/community-topics/issues/19 due to the political turmoil on Freenode.

**Comment by Andersson007** [comment]
@Jorge-Rodriguez thanks for reviewing!

**Pull request merged**
