### PR TITLE
mysql_user: refactor to reduce execute() calls

### PR DESCRIPTION
**Pull request by steveteahan**
##### SUMMARY

This module does not currently log the SQL statements that it executes.
A change was proposed to add this functionality, but it would require
modifications in many sections of the code due to how many cursor.execute()
statements there currently are. This change simply consolidates the
number of execute() calls where it is trivial to do so.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
mysql_user

##### ADDITIONAL INFORMATION

Without this change, logging the queries in my change proposed in #75 would either look like:

```
# repeating the query text and prone to error on changes
log_query(*mogrify("CREATE USER %s@%s IDENTIFIED BY PASSWORD %s", (user, host, password), tls_requires))
cursor.execute(*mogrify("CREATE USER %s@%s IDENTIFIED BY PASSWORD %s", (user, host, password), tls_requires))
```

or

```
# avoids repeating the query, but turns 1 line into 3 everywhere where the query will be logged (7 times in `user_add` alone)
query_with_args = mogrify("CREATE USER %s@%s IDENTIFIED BY PASSWORD %s", (user, host, password), tls_requires)
log_query(*query_with_args)
cursor.execute(*query_with_args)
```

Overall, even if I were to create a `execute_and_log` method, the proposed changes would still be an improvement in readability.

### CODE REVIEW

**Comment by steveteahan** [comment]
It doesn't look like the plugin parameters had any testing.  The `encrypted` parameter test was dropped here: https://github.com/ansible/ansible/pull/25825/files

I'm assuming that I'll hit this issue in #75 even without refactoring due to the number of plugin-related branches.  I'm not very familiar with other auth plugins, but I can take a look at what it'd take to fix the `encrypted` test and add a tests for plugins.

**Comment by Andersson007** [comment]
from my personal experience: we should cover all changed parts:), i.e. to keep CI green

**Comment by steveteahan** [comment]
I believe this should be unblocked as soon as #79 is merged.  That PR adds test coverage that was missing for the majority of password and plugin authentication paths.

**Comment by Andersson007** [comment]
@steveteahan could you please rebase the branch and fix the conflicts

**Comment by Andersson007** [comment]
@steveteahan if the tests get green, will try to review the PR tomorrow (if nothing super urgent on my day work), thanks for working on this

**Review by Andersson007 — APPROVED** [review]

**Comment by Andersson007** [comment]
@bmalynovytch what do you think? It's a kinda preparation for https://github.com/ansible-collections/community.mysql/issues/75

**Review by bmalynovytch — APPROVED** [review]
> @bmalynovytch what do you think? It's a kinda preparation for #75

Looks good to me, although I didn't test it.

**Comment by Andersson007** [comment]
@steveteahan thanks for the refactoring!
@bmalynovytch thanks for reviewing! Now i can be sure we will fix hypothetical consequences together;)
Merged

**Pull request merged**
