### PR TITLE
fix connection arguments for MySQLdb <2.0 !=1.0

### LINKED ISSUE #546: Possible recurrence of issue #151 following latest release of community.mysql?
##### SUMMARY
A Github Action which we run on a weekly basis, and which calls an Ansible playbook which in turn calls community.mysql, is failing since this weekend on all calls to community.mysql 

Nothing has changed in the codebase; this was confirmed as working last weekend, and so I presume the issue is with the most recent release 3.7.0.  Running the playbook by hand, in a different environment with an earlier version of community.mysql, works.

For example see below (with some details redacted):
```
- name: create heartbeat user
  community.mysql.mysql_user:
<snip>
    state: present
  when: db_role == "{{ master_role }}"
```

This produces an error like the following:
```
fatal: [<hostname>]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: 'database' is an invalid keyword argument for this function"}
```

**Note:** The error message would seem to be the same as in this issue: https://github.com/ansible-collections/community.mysql/issues/151.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
mysql_user, mysql_query, possibly others

##### ANSIBLE VERSION
```
ansible.posix:1.5.2
```
##### COLLECTION VERSION
```
community.mysql:3.7.0
```

##### OS / ENVIRONMENT
Github Action environment as described below:
```
Current runner version: '2.304.0'
Runner name: 'infra-runners-default-tr8[2](https://github.com/RentTheRunway/mysql/actions/runs/4904303710/jobs/8757254064#step:1:2)k-cqkkn'
Runner group name: 'infra-runners'
Machine name: 'infra-runners-default-tr82k-cqkkn'
GITHUB_TOKEN Permissions

Starting galaxy role install process
- downloading role 'google_cloud_ops_agents', owned by googlecloudplatform
- downloading role from https://github.com/GoogleCloudPlatform/stackdriver-ansible-role/archive/master.tar.gz
- extracting googlecloudplatform.google_cloud_ops_agents to /home/runner/.ansible/roles/googlecloudplatform.google_cloud_ops_agents
- googlecloudplatform.google_cloud_ops_agents (master) was installed successfully
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/ansible-posix-1.5.2.tar.gz to /home/runner/.ansible/tmp/ansible-local-508_auvsywe/tmpfntsf2t8/ansible-posix-1.5.2-zzhqpkox
Installing 'ansible.posix:1.5.2' to '/home/runner/.ansible/collections/ansible_collections/ansible/posix'
ansible.posix:1.5.2 was installed successfully
...
Downloading https://galaxy.ansible.com/download/community-mysql-3.7.0.tar.gz to /home/runner/.ansible/tmp/ansible-local-508_auvsywe/tmpfntsf2t8/community-mysql-3.7.0-bubguzl8
Installing 'community.mysql:3.7.0' to '/home/runner/.ansible/collections/ansible_collections/community/mysql'
community.mysql:3.7.0 was installed successfully
Downloading https://galaxy.ansible.com/download/community-general-6.6.0.tar.gz to /home/runner/.ansible/tmp/ansible-local-508_auvsywe/tmpfntsf2t8/community-general-6.6.0-jbn55ez8
Installing 'community.general:6.6.0' to '/home/runner/.ansible/collections/ansible_collections/community/general'
community.general:6.6.0 was installed successfully
```

##### STEPS TO REPRODUCE
Some example code blocks which are failing:

```
- name: create heartbeat user
  community.mysql.mysql_user:
<snip>
    state: present
  when: db_role == "{{ master_role }}"
```

```
- name: Provision <stuff>
  community.mysql.mysql_query:
    login_db: mysql
    query:
      - "SET sql_log_bin = 0"
      - "REPLACE INTO tablename <etc...{{variable1}} {{variable2}}...  etc>"
    named_args:
      variable1: "{{ variable1 }}"
      variable2: "{{ variable2 }}"
    single_transaction: yes
```

##### EXPECTED RESULTS
Call to community.mysql.mysql_user, mysql_query etc. completes as requested

##### ACTUAL RESULTS
Actual results for the 2 examples as above:

```
TASK [<role name> : create heartbeat user] ***********************
fatal: [<hostname>]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: 'database' is an invalid keyword argument for this function"}
```

```
TASK [<role name> : Provision <stuff>] ***
fatal: [<hostname>]: FAILED! => {"changed": false, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: 'database' is an invalid keyword argument for this function"}
```

### PR DESCRIPTION
**Pull request by betanummeric**
fixes #546 and #551

### CODE REVIEW

**Comment by betanummeric** [comment]
The CI errors appear to be unrelated to the change:
```
ERROR! [DEPRECATED]: ansible.builtin.include has been removed. Use include_tasks or import_tasks instead. This feature was removed from ansible-core in a release after 2023-05-16. Please update your playbooks.
```
occurring at: https://github.com/betanummeric/community.mysql/blob/bff05ce8ddb99f53270ad11e753c153df604adb5/tests/integration/targets/test_mysql_variables/tasks/mysql_variables.yml#L40

**Review by Andersson007 — APPROVED** [review]
@betanummeric feel free to merge it as is or fix the unrelated line and merge it after, as you prefer

**Comment by Andersson007** [comment]
oh, it seems to be not as streightforward as we thought. maybe as there are still not a lot of unrelated-to-this-fix change maybe revert last to commits and merge it as it was originally? (just a suggestion, if you like we could merge all stuff here)

**Comment by betanummeric** [comment]
It appears to be just syntax errors, but in many places, hence tedious to fix. Let's fix that in another PR, I will revert the attempt to fix it here.

**Comment by Andersson007** [comment]
> It appears to be just syntax errors, but in many places, hence tedious to fix. Let's fix that in another PR, I will revert the attempt to fix it here.

SGTM, thanks

**Pull request merged**
