### PR TITLE
Patchback/backports/stable 1/51a38840d977e6184be3ef1d6f427c8cb3dc4545/pr 342

### PR DESCRIPTION
**Pull request by hubiongithub**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Andersson007** [comment]
@hubiongithub it seems that something went unexpected as i can see that the backport contains a lot of other commits. if you share how you did it (all the steps), we could help find what was missed.

**Comment by Andersson007** [comment]
@hubiongithub i would suggest:
1. git fetch upstream
2. being in main, git merge upstream/main
3. git hist | head  # copy the commit hash
4. git checkout -b backport-0 upstream/stable-1  # same for stable-2 later
5. git cherry-pick -x <commit hash>
6. it'll show you in which files the conflicts are, solve them
7. git add <file>
8. git commit -m "..."
9. git push origin backport-0
10. etc.

**Comment by hubiongithub** [comment]
13313  git remote -v
13314  git fetch upstream
13315  git checkout -b patchback/backports/stable-2/51a38840d977e6184be3ef1d6f427c8cb3dc4545/pr-342 upstream/stable-2
13316  git cherry-pick -x 51a38840d977e6184be3ef1d6f427c8cb3dc4545
13317  vi plugins/modules/mysql_user.py
13318  git push origin patchback/backports/stable-2/51a38840d977e6184be3ef1d6f427c8cb3dc4545/pr-342
13319  git add plugins/modules/mysql_user.py
13320  git commit -m "CHERRY-PICKING stable-2"
13321  git push origin patchback/backports/stable-2/51a38840d977e6184be3ef1d6f427c8cb3dc4545/pr-342
13322  git checkout issue334_fix_logic_on_oncreate
13323  git fetch upstream
13324  git checkout -b patchback/backports/stable-1/51a38840d977e6184be3ef1d6f427c8cb3dc4545/pr-342 upstream/stable-1
13325  git cherry-pick -x 51a38840d977e6184be3ef1d6f427c8cb3dc4545
13326  vi plugins/modules/mysql_user.py
13327  git add plugins/modules/mysql_user.py
13328  git commit -m "CHERRY-PICKING stable-1"
13329  git push origin patchback/backports/stable-1/51a38840d977e6184be3ef1d6f427c8cb3dc4545/pr-342
13330  git checkout issue334_fix_logic_on_oncreate

**Comment by hubiongithub** [comment]
> 3\. git hist | head

git hist | head
git: 'hist' is not a git command. See 'git --help'.

git version 2.25.1 (Ubuntu 20.04 here)

git log seems what wee want?



git log | head
commit 51a38840d977e6184be3ef1d6f427c8cb3dc4545
Author: hubiongithub <79990207+hubiongithub@users.noreply.github.com>
Date:   Tue May 31 07:40:32 2022 +0200

    mysql_user: prevent password getting set for existing users on on_cre… (#342)
    
    * mysql_user: prevent password getting set for existing users on on_create when plugin is used
    
    * added changelog fragment

**Comment by hubiongithub** [comment]
git checkout -b backport-0 upstream/stable-1
Branch 'backport-0' set up to track remote branch 'stable-1' from 'upstream'.
Switched to a new branch 'backport-0'

git cherry-pick -x 51a38840d977e6184be3ef1d6f427c8cb3dc4545

CONFLICT (content): Merge conflict in plugins/modules/mysql_user.py

edit it, git add, git commit:
git commit -m "PR379 merge"
[backport-0 1d0c077] PR379 merge
 Author: hubiongithub <79990207+hubiongithub@users.noreply.github.com>
 Date: Tue May 31 07:40:32 2022 +0200
 2 files changed, 8 insertions(+), 5 deletions(-)
 create mode 100644 changelogs/fragments/334-mysql_user_fix_logic_on_oncreate.yml

git push origin backport-0
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 4 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.18 KiB | 1.18 MiB/s, done.
Total 8 (delta 5), reused 0 (delta 0)
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
remote: 
remote: Create a pull request for 'backport-0' on GitHub by visiting:
remote:      https://github.com/hubiongithub/community.mysql/pull/new/backport-0
remote: 
To github.com:hubiongithub/community.mysql.git
 * [new branch]      backport-0 -> backport-0

PR380

will try this fpr stable-2 if this worked, sorry for the mess, but I've no idea what went wrong.

**Comment by hubiongithub** [comment]
13:04 $ git checkout main
Switched to branch 'main'
Your branch is ahead of 'origin/main' by 14 commits.
  (use "git push" to publish your local commits)
✔ ~/github.com/ansible_collections/community/community.mysql [main ↑·14|✔] 
13:09 $ git fetch upstream
✔ ~/github.com/ansible_collections/community/community.mysql [main ↑·14|✔] 
13:09 $ git merge upstream/main
Already up to date.
✔ ~/github.com/ansible_collections/community/community.mysql [main ↑·14|✔] 
13:09 $ git checkout -b backport-1 upstream/stable-2
Branch 'backport-1' set up to track remote branch 'stable-2' from 'upstream'.
Switched to a new branch 'backport-1'
✔ ~/github.com/ansible_collections/community/community.mysql [backport-1|✔] 
13:16 $ git cherry-pick -x 51a38840d977e6184be3ef1d6f427c8cb3dc4545
Auto-merging plugins/modules/mysql_user.py
CONFLICT (content): Merge conflict in plugins/modules/mysql_user.py
error: could not apply 51a3884... mysql_user: prevent password getting set for existing users on on_cre… (#342)
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
✘-1 ~/github.com/ansible_collections/community/community.mysql [backport-1|CHERRY-PICKING|●1✖ 1] 
13:17 $ vi plugins/modules/mysql_user.py
✔ ~/github.com/ansible_collections/community/community.mysql [backport-1|CHERRY-PICKING|●1✖ 1] 
13:17 $ git add plugins/modules/mysql_user.py
✔ ~/github.com/ansible_collections/community/community.mysql [backport-1|CHERRY-PICKING|●2] 
13:17 $ git commit -m "PR379 merge stable2"
[backport-1 a4fa89d] PR379 merge stable2
 Author: hubiongithub <79990207+hubiongithub@users.noreply.github.com>
 Date: Tue May 31 07:40:32 2022 +0200
 2 files changed, 8 insertions(+), 5 deletions(-)
 create mode 100644 changelogs/fragments/334-mysql_user_fix_logic_on_oncreate.yml
✔ ~/github.com/ansible_collections/community/community.mysql [backport-1 ↑·1|✔] 
13:17 $ git push origin backport-1
Enumerating objects: 14, done.
Counting objects: 100% (14/14), done.
Delta compression using up to 4 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.10 KiB | 1.10 MiB/s, done.
Total 8 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
remote: 
remote: Create a pull request for 'backport-1' on GitHub by visiting:
remote:      https://github.com/hubiongithub/community.mysql/pull/new/backport-1
remote: 
To github.com:hubiongithub/community.mysql.git
 * [new branch]      backport-1 -> backport-1

**Comment by Andersson007** [comment]
strange. Let me create backport PRs

**Comment by Andersson007** [comment]
@hubiongithub you're doing everything right, just need to choose `stable-1` when opening the PR, not `main`. We already have these changes in `main`.
We have stable-1 branch for 1.* releases and stable-2 for 2.* version releases. So we need to backport your changes so that users of those versions will be able to get the update after the next release.
Could you open the same against `stable-1`?

**Pull request closed without merging**
