### PR TITLE
Mark mysql_replication's master_ssl_key option as no_log=False

### PR DESCRIPTION
**Pull request by felixfontein**
##### SUMMARY
Should fix CI (sanity tests currently fail because of that).

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
mysql_replication

### CODE REVIEW

**Comment by felixfontein** [comment]
I didn't add a changelog fragment since this should not be user-facing. If you'd like to have one, please tell me :)

CC @Andersson007

**Comment by felixfontein** [comment]
Also please someone verify that this is indeed not a secret. I didn't find any documentation on such a MySQL variable, but similar ones seemed to be filenames (and not the secret key itself), so I *assume* it's the same here.

If my assumption is wrong, this should be a security fix and `no_log` should be set to `True`.

**Comment by Andersson007** [comment]
@felixfontein yeah, it's a path https://dev.mysql.com/doc/refman/8.0/en/replication-solutions-encrypted-connections.html,
thanks for the fix!:)

**Comment by felixfontein** [comment]
@Andersson007 thanks! It might make sense to link to these docs from the options then ;-)

**Comment by Andersson007** [comment]
@felixfontein good spot, will think, thanks:)

**Pull request merged**
