### PR TITLE
mysql_replication: remove mode values and ret values containing master / slave

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to
https://github.com/ansible-collections/community.mysql/issues/145
https://github.com/ansible-collections/community.mysql/pull/147
https://github.com/ansible-collections/community.mysql/pull/150
https://github.com/ansible-collections/community.mysql/pull/97

Will be release as a breaking change with 3.0.0

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @Jorge-Rodriguez @bmalynovytch @rsicart

**Review by Jorge-Rodriguez — APPROVED** [review]
LGTM
Should we test for expected failures when using the old terminology?

**Comment by Andersson007** [comment]
> LGTM Should we test for expected failures when using the old terminology?

Good question

**Comment by Andersson007** [comment]
@Jorge-Rodriguez the tests have been added (the more tests the alwaysbetter), thanks:)

**Review by Jorge-Rodriguez — APPROVED** [review]

**Comment by Andersson007** [comment]
@Jorge-Rodriguez thanks for reviewing!

**Comment by nerijus** [comment]
Now it does not work with mariadb versions <10.5, for example, 10.4.
If I use `slave_pos`:
```
value of primary_use_gtid must be one of: current_pos, replica_pos, disabled, got: slave_pos
```
If I use `replica_pos`:
```
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'replica_pos' at line 1")
```

**Comment by Andersson007** [comment]
@nerijus , working on this, thanks!

**Pull request merged**
