### PR TITLE
[stable-1] mysql_user: added flush privileges to write dynamic privs into db

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Backport of https://github.com/ansible-collections/community.mysql/pull/338

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
@rsicart , this is a manual backport of https://github.com/ansible-collections/community.mysql/pull/340 to stable-1, just a fyi

**Comment by rsicart** [comment]
Thanks for doing this manual backport, I've just seen that it failed

**Comment by rsicart** [comment]
LGTM

**Comment by Andersson007** [comment]
@rsicart thanks for reviewing and merging!

**Pull request merged**
