### PR TITLE
Add clarification about requirements

### LINKED ISSUE #8: Can not set mysql user password: "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}
##### SUMMARY
I have a task to create user and set update password on create. From this task, I just want to update my password once. So, if I run my task again i will not update my password again. My task run well in first run/execution. But when I run again my task I get this error:
```
"The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}
```
I have installed PyMySQL via pip and apt, still give the same errors.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]

```

##### CONFIGURATION
```
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/etc/ansible/ansible.cfg) = root

```

##### OS / ENVIRONMENT
Ansible Host: Ubuntu 18.04
Target Host: Ubuntu 18.04
Python 3

##### STEPS TO REPRODUCE

1. Run below task. It will run well.

```yaml
- name: Set clustercheck user password
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    name: clustercheck
    password: "{{ mysql_clustercheck_password }}"
    priv: '*.*:PROCESS'
    update_password: on_create
    state: present
  when:
    - inventory_hostname == groups['controller'][0]
```
2. Run again above task again will result error.
```
{"changed": false, "msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."}
```

##### EXPECTED RESULTS
No errors.

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.mysql/issues/8

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
`plugins/doc_fragments/mysql.py`

### CODE REVIEW

**Comment by Andersson007** [comment]
@Jorge-Rodriguez could you please take a look?

**Comment by Jorge-Rodriguez** [comment]
@Andersson007 Did already, looks good to me.

**Comment by Andersson007** [comment]
@Jorge-Rodriguez the more explicit way, i think, is to push the `Approve` button on the `Files changed` tab:)

**Review by Jorge-Rodriguez — APPROVED** [review]

**Comment by Jorge-Rodriguez** [comment]
What do you know? I had no idea that was there. I'm usually the one being reviewed, not the one doing the reviewing.
😄 😄

**Comment by Andersson007** [comment]
@Jorge-Rodriguez ok, thanks for reviewing ;)

**Comment by Andersson007** [comment]
.. and approving:D

**Pull request merged**
