### PR TITLE
mysql_user: when grant select on columns, the module always report the state has changed

### LINKED ISSUE #99: mysql_user column privilege show task as always changed
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

mysql_user

##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jsafieddine/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.18 (default, Aug  4 2020, 11:16:42) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Ubuntu 18.04.4 LTS
Percona Server 5.7

##### STEPS TO REPRODUCE

in MySQL:
```
CREATE DATABASE testDb;
CREATE TABLE `testDb`.`testTable`(testColA TINYINT PRIMARY KEY, testColB TINYINT, testColC TINYINT);
```

Run a play with the following task:
```yaml
- name: setup user
      mysql_user:
        name: 'testUser'
        host: 'localhost'
        password: 'password'
        priv:
          'testDb.testTable': SELECT (testColA, testColB),INSERT
        state: 'present'
      become: True
```

##### EXPECTED RESULTS

Running this task a second time shows no changes.

##### ACTUAL RESULTS

Task is always shown as changed.

I checked the output of `SHOW GRANTS FOR USER testUser@localhost;`:
```
mysql> SHOW GRANTS FOR testUser@localhost;
+---------------------------------------------------------------------------------------------+
| Grants for testUser@localhost                                                               |
+---------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'testUser'@'localhost'                                                |
| GRANT SELECT (TESTCOLB, TESTCOLA), INSERT ON `testDb`.`testTable` TO 'testUser'@'localhost' |
+---------------------------------------------------------------------------------------------+ 
```
Changing the the order of the column privileges in the Ansible Task to
```
- name: setup user
      mysql_user:
        name: 'testUser'
        host: 'localhost'
        password: 'password'
        priv:
          'testDb.testTable': SELECT (TESTCOLB, TESTCOLA), INSERT
        state: 'present'
      become: True
```
results in:
```mysql> SHOW GRANTS FOR testUser@localhost;
+---------------------------------------------------------------------------------------------+
| Grants for testUser@localhost                                                               |
+---------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'testUser'@'localhost'                                                |
| GRANT SELECT (TESTCOLA, TESTCOLB), INSERT ON `testDb`.`testTable` TO 'testUser'@'localhost' |
+---------------------------------------------------------------------------------------------+
```
So as it seems the column privileges are added/shown in reverse order as given in the task. 

```paste below

```

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Fixes https://github.com/ansible-collections/community.mysql/issues/99

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
tests/integration/targets/test_mysql_user/tasks/test_priv_dict.yml

### CODE REVIEW

**Comment by Andersson007** [comment]
sorry folks for spam, I'm temporary not in a permanent apartment, so I have limited resources to run mysql tests locally on my notebook...

**Comment by Andersson007** [comment]
@bmalynovytch @Jorge-Rodriguez @steveteahan ready for review

**Review by Jorge-Rodriguez — APPROVED** [review]

**Comment by Andersson007** [comment]
@Jorge-Rodriguez thanks for approving! I decided to add unit tests as well, hope nothing will need to change in the code after adding:)

**Comment by bmalynovytch** [comment]
Hi @Andersson007 !
This change is quite big.
I'll need more time to review it properly 🙁

**Comment by Andersson007** [comment]
@bmalynovytch sure, take your time! Thanks! Is a week enough?
I also added the unit tests, hope it'll help understand what's going on here

**Comment by Andersson007** [comment]
@Jorge-Rodriguez thanks for reviewing!

**Comment by ghost** [comment]
Hi there, I hope it is fine to write a comment here after the PR is merged. I had a look at the changes and wanted to let you know that there are more column privileges than SELECT. 

> The permissible priv_type values for a column (that is, when you use a column_list clause) are INSERT, REFERENCES, SELECT, and UPDATE. 

Copied from: https://dev.mysql.com/doc/refman/8.0/en/grant.html#grant-column-privileges

Should I open a new issue for this or can this still be fixed here?

**Comment by Jorge-Rodriguez** [comment]
@JaSafieddine the best would be to open a new issue and reference this PR and issue #99 in it.

Thanks for the heads up!

**Comment by Andersson007** [comment]
@JaSafieddine @Jorge-Rodriguez thanks
I'm not a guru of mysql, so thanks very much! I think it won't be very hard to adjust the merged stuff

**Pull request merged**
