### PR TITLE
[PR #416/97318559 backport][stable-1] Fix ci python requirements

### PR DESCRIPTION
**Pull request by laurent-indermuehle**
* Add matrix for python and ansible-core versions for sanity tests

* Add python 3.9 to integrations tests

* Add python 3.9 to unit tests

* Reformat sort by python version first

(cherry picked from commit 97318559e5aa976dce668a62daaab258014d75a9)

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by laurent-indermuehle** [comment]
After I've compared stable-1 and stable-2 I decided I can merge my conflict resolution from stable-2 to stable-1.

But now, the CI si failing with errors never seen before.

I've no clue what is going on. Maybe this errors were already there. I'll need to check older runs. Don't have time to do that until next week.

Also I'm wondering if it makes sense to test stable-1 against 2.13 and devel... Ho long is the the support for this branch?

**Comment by Andersson007** [comment]
>Also I'm wondering if it makes sense to test stable-1 against 2.13 and devel... Ho long is the the support for this branch?

I think it makes sense as the collection (supported versions) have to work with all of the supported versions of ansible-core.
The rule is that we support the current version + 2 previous (i.e. in this case 3, 2, 1). When c.mysql 4.0.0 is released, we'll drop support for version 1.

**Comment by Andersson007** [comment]
@laurent-indermuehle I think if we test against stable-2 and `main`, let's make it just working here with `stable-1` by limiting the scope excluding devel and stable-2.13. It should be fine as we test against all supported branches in the other branches. Feel free to exclude them.

**Comment by laurent-indermuehle** [comment]
Thanks @Andersson007 for the proposed solution.
I'll try that soon.

**Comment by laurent-indermuehle** [comment]
Excluding 2.13 and devel would not have solved the issue because the integrations' tests are failing also when using 2.12.
So I decided to give a try to fix the error:  1292, \"Truncated incorrect max_connect_errors value: '-1'\
Will see in a few hours if I'm correct.

**Comment by laurent-indermuehle** [comment]
Silly me, it's a test intended to fail.
The issue is the assert changed == true that receive a false. But a failed task can return changed : true ?
I've checked, this happen only in stable-1
Just pushed 2 fixes, will see tomorrow.

**Comment by laurent-indermuehle** [comment]
I checked the variable "changed" inside [tests/integration/targets/test_mysql_variables/tasks/assert_var.yml](https://github.com/ansible-collections/community.mysql/blob/stable-1/tests/integration/targets/test_mysql_variables/tasks/assert_var.yml) and it is "undefined".
Why?

**Comment by Andersson007** [comment]
> I checked the variable "changed" inside [tests/integration/targets/test_mysql_variables/tasks/assert_var.yml](https://github.com/ansible-collections/community.mysql/blob/stable-1/tests/integration/targets/test_mysql_variables/tasks/assert_var.yml) and it is "undefined". Why?

good question:)

**Comment by laurent-indermuehle** [comment]
To reproduce the issue, the file https://github.com/ansible-collections/community.mysql/blob/stable-1/tests/integration/targets/setup_mysql/vars/main.yml must be modified as such:

```yaml
# python_packages: [pymysql == 0.9.3]
python_packages: [mysqlclient == 2.0.1]
```

**Comment by laurent-indermuehle** [comment]
Question, is older version of Ansible had a different assert module? I ask this, because the Jinja templating mustaches seams unnecessary to me here:

```yaml
assert:
    that:
      - "output.changed == {{ changed }}"
```
And in fact, if I remove them, I then get the following error on every tests :

```yaml
TASK [test_mysql_variables : assert output message changed value] ************************************************************************************************************************
fatal: [testhost]: FAILED! => {
    "assertion": "output.changed == changed",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}
```

**Comment by Andersson007** [comment]
if the error's scope is limited, you can just remove it. I don't think the error is related to our code

**Comment by laurent-indermuehle** [comment]
Ok, Now i'm left with only pymsql 0.7 and 0.9 that fails to connect to the sandboxed database. login_user and login_password is rejected. Then it fails to find a /root/.my.cnf (which is normal because it is located in "{{ dbdeployer_sandbox_home_dir }}/multi_msb_{{ install_version|replace('.','_') }}/node1/my.sandbox.cnf" which translate to /root/sandboxes/multi_msb_8_0_22/node1/my.sandbox.cnf).

But why mysqlclient succeed all tests? That makes no sense :(

**Comment by Andersson007** [comment]
@laurent-indermuehle thanks for fixing the tests!

**Comment by laurent-indermuehle** [comment]
You're welcome. And I'm not done ;) 
https://github.com/laurent-indermuehle/community.mysql/commits/port-stable-1-ci-changes

**Pull request merged**
