### PR TITLE
Fix issues and documentation with integration tests after merge of #490.

### PR DESCRIPTION
**Pull request by laurent-indermuehle**
##### SUMMARY

This PR will fix documentation and issues with integration tests after merge of #490.
The main issue is that containers published in ansible-collections are marked "private" and therefore are not usable for local tests. Or maybe each contributor will be asked to create an access token. I'll have to investigate. I'll update this PR  as I progress.

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME

- CI
- Testing

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by laurent-indermuehle** [comment]
Ready for review !

NOTE TO SELF: Update the wiki if this PR is accepted.
NOTE TO @Andersson007 : After merge, can you please:
  - Delete all packages containing `my80`, `mariadb103` and `mariadb106` (but keep `my57`)
  - Mark public all packages containing `-mysql-` and `-mariadb-`
IMPORTANT : Before merge, update the link to docker_image from `laurent-indermuehle` to `ansible-collections`.

**Review by Andersson007 — APPROVED** [review]
@laurent-indermuehle feel free to merge
Please let me know when i can remove those packages you mentioned

**Comment by laurent-indermuehle** [comment]
@Andersson007 great, thank you.

I have changed back the path to the docker image and will merge soon.
I'll have to backport #490 and this one to stable1 and stable2 before you can do the cleanup in packages. I'll notify you when I'm done.

**Comment by laurent-indermuehle** [comment]
@Andersson007 : I finished merging to stable-1 and stable-2. In a few hours (To let all Docker image related workflow finish) can you please:

* Delete all packages containing `my80`, `mariadb103` and `mariadb106` (but keep `my57`, `-mysql-` and `-mariadb-`)? It should be 15 images left.
* Mark public all packages

Thanks for your help!

**Comment by Andersson007** [comment]
@laurent-indermuehle done, yes, there are 15 left, all should be public, thanks!

**Pull request merged**
